# File: azure-pipelines\maven-release\common4j.yml
# Description: Publish common4j to maven central (sonatype)
# https://search.maven.org/search?q=g:com.microsoft.identity%20AND%20a:common4j
# Variable: 'common4jVersion' was defined in the Variables tab
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

resources:
  repositories:
  - repository: self
    type: git
    ref: master

jobs:
- template: ../templates/steps/maven-release/maven-release-jobs.yml
  parameters:
    project: common4j
    projectVersion: $(common4jVersion)
    gradleAssembleReleaseTask: common4j:clean common4j:assemble common4j:test -Psugar=true
    gradleGeneratePomFiletask: common4j:generatePomFileForAarPublication
    jarSourceFolder: common4j\build\outputs\jars
    pomSourceFolder: common4j\build\publications\aar
    extraSourceFolder: common4j\build\libs
    extraContents: '**/*.jar'
    gpgAar: false
    gpgSourcesJar: true
    gpgJavadocJar: true
    gpgJar: true
